### ISSUE TITLE
Promote/Demote/Kick Group Users

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#654]
**Is your feature request related to a problem? Please describe.**
Currently there is only one Admin per group being the person that created that group. 

**Describe the solution you'd like**
We would like to have admins be able to kick members from the group, admins to be able to promote members to admins.

**Things to think about**
Permissions in this can get weird for example, once a user is an admin they can't be kicked by another admin or demote as once a member becomes admin they can just kick the original admin. Also being admin gives the power to delete a group. So might want to give the original creator some exclusive rights like demoting/kicking other admins and being the only one that can delete a group.

**Tasks**

*Backend*

- [ ] Add three new endpoints. "/api/groups/:id/kick", "/api/groups/:id/promote", "/api/groups/:id/demote" with respective kickUser, promoteUser and demoteUser functions in the Group Model. Preform proper permission checking.
- [ ] Add tests for each of these routes testing with different user permissions.

*Frontend*

- [ ] Add a pop up / buttons so the user can actually promote/demote/kick.
- [ ] On Click call the appropriate endpoint and update the existing lists.

**Files of Interest**
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/frontend/src/pages/GroupEdit/GroupEdit.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/groups.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/groups.test.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/models/Group.js

**Comment by hbh7** [comment]
Good issue, and even better design consideration. I think to keep things simple, let's probably just stick with you're an admin or you're not, and you just shouldn't promote people to admin that you don't trust. Perhaps we can evaluate a more sophisticated permissions system in the future, but for now a simple system is probably best.

As for endpoint names, I get where you're coming from with kickUser, but I worry that our members who don't have English as their native language may not find the names as intuitive as we'd like them to be. Plus, just having them under the group/id/ endpoints doesn't necessarily imply that those routes like promote/demote are talking about users. Perhaps we want to go with something like addadmin, removeadmin, removeuser, adduser. I don't love that there's not a great way to do multi-word routes and have them be highly readable and pretty. I suppose since it's a backend endpoint anyways, things I usually find offensive like - or _ would be fine as word separators, but despite URLs being case sensitive, I don't think camelCase is a great idea. 

Thoughts?
