### ISSUE TITLE
User Polls

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#655]
**Is your feature request related to a problem? Please describe.**
Polls are a pollbuddy wide feature and not just a groups feature. We want to allow users to create polls without having to be in a group. The main benefit of this is to use the RequiresLogin feature of a poll. Every poll on a group requires the user to be logged in and maybe users might just want anyone to be able to contribute to poll even if they are not logged in.

**Describe the solution you'd like**

**Tasks**

*Backend*
- [ ] Add endpoint for users to receive all their polls that they created. This will be an "/api/users/me/polls" route with a getPolls function in the User Model. Use Mongo.Collections.Find({Creator: userID}).
- [ ] Add tests to the user tests to ensure proper functionalility.
- [ ] Add requiresLogin to the editPollValidator to allow for users to update this value. Update respective tests. 
- [ ] Add requiresLogin to the getPoll return so we can return this value to users. Update respective tests.

*Frontend*

- [ ] Add a polls page. This will include a list of the polls and buttons to redirect to the poll editor page. Suggestion: Currently the "/polls" page is not used for anything so this page might be a good spot to add all of the user polls. 
- [ ] Add My Polls to Homepage and to Header Dropdown so users can be directed there.
- [ ] Add Requires Login checkbox to the poll editor page. Might want to only display the checkbox if it is a user poll. As Requires Login does not matter for a group poll. Update the call to the backend to include that value.

**Files of Interest**
https://github.com/PollBuddy/PollBuddy/tree/master/PollBuddy-Server/frontend/src/pages/PollEditor
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/models/User.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/models/Poll.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/users.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/users.test.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/polls.test.js
