### ISSUE TITLE
Poll OpenTime and CloseTime

### ISSUE THREAD

**Issue by PrinxeShamar** [PollBuddy/PollBuddy#660]
**Is your feature request related to a problem? Please describe.**
Currently the poll creator has to directly manage when the poll opens and poll closes via directly selection the Allow Submissions button. 

**Describe the solution you'd like**
We want users to be able to set a StartTime from which users can assess the poll to the CloseTime. Members can view and submit during these times.

**Task**

Backend

- [ ] Add OpenTime and CloseTime to the Poll Schema and pollEditValidator.
- [ ] Add the openTime and closeTime to the getPoll results.
- [ ] Go Nessecary checks on the getPoll. Check that the current time is in between OpenTime and CloseTime if they are a group member. Also should add these checks to the submitQuestion function.

Frontend

- [ ] Add OpenTime and CloseTime to the Poll Editor box.
- [ ] Pass these values to the backend

**Files to edit**
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/models/Poll.js
https://github.com/PollBuddy/PollBuddy/blob/master/PollBuddy-Server/backend/routes/polls.test.js
https://github.com/PollBuddy/PollBuddy/tree/master/PollBuddy-Server/frontend/src/pages/PollEditor
